const {writeFileSync, readFileSync, copyFile, mkdir} = window.fs
const {join, dirname} = window.path
const savesPath = localStorage.getItem('savesPath')
const currentSave = localStorage.getItem('currentSave')
const subMaps = join(savesPath, currentSave, 'maps')
const map = localStorage.getItem('map')
const tempPath = join(savesPath, currentSave, map)
const quickLoactionsPath = join(savesPath, currentSave, 'quickLocations.json')
var data = JSON.parse(readFileSync(tempPath, 'utf-8'))
var tool = 'cursor'
var isDown = false
var target = undefined
var Ltarget = undefined
let previousX = undefined;
let previousY = undefined
const options = ['Castle', 'City', 'Village', 'Bridge', 'Mountain', 'Volcano', 'Cave', 'Lake', 'Nest', 'Party']